name:                hs-sql-parser
version:             0.1.0.0
github:              "sanojmg/hs-sql-parser"
license:             Apache-2.0
author:              "Sanoj MG"
maintainer:          ""
copyright:           "2021 Sanoj MG"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A parser for simple SQL like queries
# category:            Parser

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sanojmg/hs-sql-parser#readme>

default-extensions:
- TemplateHaskell
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- directory
- filepath
- optparse-applicative
- parsec
- wreq
- HUnit
- prettyprinter

library:
  source-dirs: src

executables:
  hs-sql-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-sql-parser
    default-extensions:
    - TemplateHaskell
    - OverloadedStrings

tests:
  hs-sql-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-sql-parser
    default-extensions:
    - TemplateHaskell
    - OverloadedStrings
